### ISSUE TITLE
Does it support trying to support PTS point cloud

### ISSUE THREAD

**Issue by AllenAlise** [Oslandia/py3dtiles#60]
I tried running it using `PTS `point cloud，The following error occurs：
`Traceback (most recent call last):
  File "E:/GitProject/NEWpy3dtiles/py3dtiles/convert.py", line 803, in <module>
    main(args)
  File "E:/GitProject/NEWpy3dtiles/py3dtiles/convert.py", line 596, in main
    args.rgb)
  File "E:/GitProject/NEWpy3dtiles/py3dtiles/convert.py", line 69, in write_tileset
    for child in root_tileset['children']:
KeyError: 'children'`

**Comment by autra** [comment]
Hi @AllenAlise at the moment, py3dtiles only supports las and xyz file format. Contributions are welcomed to add it!

**Comment by delhomer** [comment]
Moved to https://gitlab.com/Oslandia/py3dtiles/-/issues/60
